//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 12:02:02 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://alexeisherkhonov.ru/app/endpoints", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.alexeisherkhonov.app.endpoints;
